name: TestsMSI

on:
  workflow_dispatch:
  push:
    branches:
    - 'main'
    - '3.11'
    - '3.10'
    - '3.9'
    - '3.8'
    - '3.7'
    paths:
    - 'Tools/msi/**'
    - '.github/workflows/build_msi.yml'
  pull_request:
    branches:
    - 'main'
    - '3.11'
    - '3.10'
    - '3.9'
    - '3.8'
    - '3.7'
    paths:
    - 'Tools/msi/**'


permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true



  build_win_amd64:
    name: 'Windows (x64) Installer'
    runs-on: windows-latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - name: Build CPython installer
      run: .\Tools\msi\buildrelease.bat -x64

    - name: Zip amd64 folder
      shell: pwsh # 使用PowerShell打包
      run: |
        Compress-Archive -Path .\PCbuild\amd64 -DestinationPath python-3.11.zip

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1 # 使用官方Action创建发布
      env:
        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }} # 主仓库token
      with:
        tag_name: Python_311 # 使用提取的标签名称
        release_name: Python_311 # 发布名称
        draft: false # 非草稿模式
        prerelease: false # 非预发布

    - name: Upload ZIP Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: python-3.11.zip
        asset_name: python-3.11.zip
        asset_content_type: application/zip # ZIP文件类型
